### ISSUE TITLE
Pretrained 3d model

### ISSUE THREAD

**Issue by ivandon15** [HannesStark/self-supervised-graphs#11]
Hello,
After reading the paper and part of the code (might be difficult for me to understand), I understand that you have a 3d model but not pre-trained, right?
If I misunderstood, could you tell me how I should use the 3d pre-trained model.
Thanks for your help!

**Comment by HannesStark** [comment]
The 3D model indeed is not pretrained and we do not provide any 3D model that is pretrained in this repository.
The point of 3DInfomax is to embue a 2D model with reasoning about 3D structure.
