### ISSUE TITLE
Embedding views in NTXentMultiplePositiveLoss

### ISSUE THREAD

**Issue by arunppsg** [HannesStark/self-supervised-graphs#15]
In this line,
https://github.com/HannesStark/3DInfomax/blob/5cd32629c690e119bcae8726acedefdb0aa037fc/commons/losses.py?plain=1#L231
 shouldn't `z2` be `z1`?

**Comment by quangnguyenbn99** [comment]
Since the author intended to reshape the z2 to z1, I believe this is merely a minor error resulting from an inadvertent copy-and-paste action.
