### ISSUE TITLE
"conda env create" problem

### ISSUE THREAD

**Issue by YuhangXiao1103** [HannesStark/self-supervised-graphs#17]
![image](https://github.com/HannesStark/3DInfomax/assets/125982410/f48775ee-1c42-4732-af2c-352ef927ce6b)
Hi, sorry to bother you.
Could you please to teach me how to deal with the problem in screenshot?

**Comment by HannesStark** [comment]
I think this would be the most useful resource for that: https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html
