### ISSUE TITLE
 What model is gin.py? 

### ISSUE THREAD

**Issue by MianWang11111** [HannesStark/self-supervised-graphs#7]
What model is gin.py? Graph isomorphic neural network? Are there references?
![image](https://user-images.githubusercontent.com/90679230/154642520-6094b671-76ae-4b7e-afe9-5b0a6760d6a6.png)
![image](https://user-images.githubusercontent.com/90679230/154642640-91b42f05-6dce-486e-ba92-4c16dbbe743a.png)

**Comment by MianWang11111** [comment]
Thank you for your help~~~

**Comment by MianWang11111** [comment]
Could you please tell me what is the model of OGBGNN?

**Comment by HannesStark** [comment]
Hi,
The gin.py file contains a graph isomorphism network implementation.
If you need an implementation of graph isomorphism network I recommend using the official implementation instead. 

Is that the information you are looking for?

**Comment by MianWang11111** [comment]
Yes~~Thank you very much.
