### ISSUE TITLE
What is the MAE of QM9? Which parameter in the following operation result is Mean Absolute Error? Thank you.

### ISSUE THREAD

**Issue by MianWang11111** [HannesStark/self-supervised-graphs#8]
![image](https://user-images.githubusercontent.com/90679230/156913822-4df9bc54-54e8-4cfe-803a-56e5fe36fd80.png)

![image](https://user-images.githubusercontent.com/90679230/156913833-ad3fa8c4-c005-44ce-b1e8-f7346add1b65.png)

**Comment by HannesStark** [comment]
It is the mae_denormalized which is the same as homo
