### ISSUE TITLE
Where is the "bbbpscaffold123.pkl"? And what is the "bbbpscaffold123.pkl"?

### ISSUE THREAD

**Issue by MianWang11111** [HannesStark/self-supervised-graphs#9]
![image](https://user-images.githubusercontent.com/90679230/161975086-f8c17937-fbb0-4942-b6d6-203889c11881.png)
I found the dataset of "BBBP.csv". Where is the "bbbpscaffold123.pkl"? And what is the "bbbpscaffold123.pkl"? Thank you very much for helping me.

**Comment by HannesStark** [comment]
That should be downloaded if you use the bbbp dataset from OGB.
This dataset does not automatically download the bbbp dataset but only uses the files after they were downloaded.

If you run the  GraphPropPredDataset from OBG with "bbbp" as parameter it will be downloaded.
You can also use the dataset that is already in the repo to download the files which has the class name "OGBGDatasetExtension"
